### ISSUE TITLE
YouTube API - Low Code CDK

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/DeveloperWeek-Connector-Contest#1]
link api

**Comment by bala-ceg** [comment]
@RealChrisSean, I saw Connector available for youtube-analytics API in airbyte, but there is none available for [youtube data API](https://developers.google.com/youtube/v3/docs/)

Can i work on it by creating a new issue for this hackathon? please confirm

**Comment by bala-ceg** [comment]
Thank you @RealChrisSean

**Comment by bala-ceg** [comment]
[PR-25863](https://github.com/airbytehq/airbyte/pull/25863) has been raised for this issue
