### ISSUE TITLE
Graylog

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/DeveloperWeek-Connector-Contest#15]
https://go2docs.graylog.org/5-0/setting_up_graylog/rest_api.html

**Comment by Alcadeus0** [comment]
@RealChrisSean I'll take this up :)

**Comment by RealChrisSean** [comment]
@Alcadeus0 amazing this has been assigned to you :).

**Comment by Alcadeus0** [comment]
@RealChrisSean this seems far complex for me :( 
I'll take some other issue up instead
