### ISSUE TITLE
Recharge

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/DeveloperWeek-Connector-Contest#16]
https://docs.airbyte.com/integrations/sources/recharge/

**Comment by subhamX** [comment]
Hi. is this issue up for grabs?

**Comment by RealChrisSean** [comment]
Yup!

**Comment by subhamX** [comment]
I realized that even a simple thing like account creation is bit tricky on rechargepayments. :( I'm reaching out the customer service, and hopefully they help me with the creds. 

Would definitely love to work on it for sure if I'm successful in getting the API keys. Shall keep you posted.

**Comment by subhamX** [comment]
update: rechargepayment folks are just unresponsive. 😥 Maybe we need to reach out to someone from engineering team via LinkedIn. Lol. Dropping my assignment to get more visibility on the issue.
