### ISSUE TITLE
Sendgrid

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/DeveloperWeek-Connector-Contest#17]
https://docs.airbyte.com/integrations/sources/sendgrid

**Comment by bala-ceg** [comment]
@RealChrisSean Please assign this issue to me

**Comment by RealChrisSean** [comment]
Done :)

**Comment by subhamX** [comment]
Hi @bala-ceg, since you're already working on #12, let me know if I can chime in for this one. 🙂

**Comment by RealChrisSean** [comment]
@bala-ceg you can only work on one connector at a time. Did you finish the other connector?

**Comment by bala-ceg** [comment]
Yes, I finished the other connector and I am going to raise PR. Nevertheless @subhamX can work on it

**Comment by RealChrisSean** [comment]
It looks like this wasn't merged. I will close this. Thank you for trying.
