### ISSUE TITLE
Mailchimp

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/DeveloperWeek-Connector-Contest#20]
https://docs.airbyte.com/integrations/sources/mailchimp

**Comment by amogh-opsverse** [comment]
I'll work on this.

**Comment by pabloescoder** [comment]
@RealChrisSean I would like to work on this!

**Comment by RealChrisSean** [comment]
This has been assigned to you :)

**Comment by RealChrisSean** [comment]
not merged
