### ISSUE TITLE
Plaid Connector

### ISSUE THREAD

**Issue by bala-ceg** [airbytehq/DeveloperWeek-Connector-Contest#27]
API Doc Reference:
https://developers.google.com/youtube/v3/docs/

**Comment by bala-ceg** [comment]
I would like to work on this issue.

**Comment by RealChrisSean** [comment]
For this contest we ask that you please only work on a connector on issues we created or migrate any alpha connectors (and up) that currently exist into the ui builder/low code cdk :).

**Comment by bala-ceg** [comment]
Thank you @RealChrisSean for letting me know. in that case i found plaid & surveycto connectors will fit into that. 
can i work on it? please let me know

**Comment by RealChrisSean** [comment]
If it's an existing connector yes :) can you please change the title of this issue to reflect the new connector you're working on?

**Comment by RealChrisSean** [comment]
Not merged
